### ISSUE TITLE
Source code ?

### ISSUE THREAD

**Issue by demaisj** [asakaz/rewards.gg-tickets-bot#2]
Hi,

By curiosity I checked your project but I didn't see any (readable) source code. All I can see here is compiled code & some manifests.
Would you plan to upload your source code on GitHub, as it is a place for open-source projects ?

Don't worry there is no hate or anger in this issue, I just had this question by curiosity.

Thanks.

**Comment by asakaz** [comment]
Oh yeah the source is very simple and written in vb.net, I don't know how I forgot to upload it but hold on I will. Also this program isn't anything special like yours it just runs the site quietly in a fast browser in the background.

**Comment by asakaz** [comment]
Okay I added the source:
https://github.com/asakaz/rewards.gg-tickets-bot/tree/master/src

Enjoy I guess.
